### PR TITLE
Test several pytorch versions in travis

### PR DESCRIPTION
**Pull request by BenjaminBossan**
For now, just an experiment to see if this works.

### CODE REVIEW

**Comment by thomasjpfan** [comment]
It looks like it works. How many versions of pytorch do we want to support? 

I would say around around 2-3 versions. For reference here are the release dates for pytorch: https://github.com/pytorch/pytorch/tags

**Comment by BenjaminBossan** [comment]
I was wondering whether we should try to support as many as possible _as long as the cost is low enough_. If we encounter something very annoying in an old version, I would consider dropping its support. When we don't officially support older versions, some people might not use skorch anymore.

My main concern is actually that the CI could take to long and time out if we test too many versions.

My suggestion for this PR would be:
* wait for pytorch 1.4 package on conda forge
* update README to make it clear which pytorch versions we support

**Comment by thomasjpfan** [comment]
That makes sense. It seems to be not many breaking changes in pytorch that affects us.

As for breaking changes in PyTorch 1.4 maybe https://github.com/pytorch/pytorch/pull/26423 will cause some issues.

**Comment by BenjaminBossan** [comment]
So I believe there is no dedicated `pytorch-cpu` package anymore. This is what I find when I search:

```
$ conda search -c pytorch pytorch | grep "1.4"
pytorch                        0.3.0 py27_cuda7.5.18_cudnn6.0.21hc114ab0_4  pytorch             
pytorch                        0.3.0 py27_cuda9.0.176_cudnn7.0.3_nccl2h301e181_4  pytorch             
pytorch                        0.4.1 py27_cuda9.2.148_cudnn7.1.4_1  pytorch             
pytorch                        0.4.1 py35_cuda9.2.148_cudnn7.1.4_1  pytorch             
pytorch                        0.4.1 py36_cuda9.2.148_cudnn7.1.4_1  pytorch             
pytorch                        0.4.1 py37_cuda9.2.148_cudnn7.1.4_1  pytorch             
pytorch                        1.4.0     py2.7_cpu_0  pytorch             
pytorch                        1.4.0 py2.7_cuda10.0.130_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py2.7_cuda10.1.243_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py2.7_cuda9.2.148_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0     py3.5_cpu_0  pytorch             
pytorch                        1.4.0 py3.5_cuda10.0.130_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py3.5_cuda10.1.243_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py3.5_cuda9.2.148_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0     py3.6_cpu_0  pytorch             
pytorch                        1.4.0 py3.6_cuda10.0.130_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py3.6_cuda10.1.243_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py3.6_cuda9.2.148_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0     py3.7_cpu_0  pytorch             
pytorch                        1.4.0 py3.7_cuda10.0.130_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py3.7_cuda10.1.243_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py3.7_cuda9.2.148_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0     py3.8_cpu_0  pytorch             
pytorch                        1.4.0 py3.8_cuda10.0.130_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py3.8_cuda10.1.243_cudnn7.6.3_0  pytorch             
pytorch                        1.4.0 py3.8_cuda9.2.148_cudnn7.6.3_0  pytorch
```

So there are CPU versions but they're bound to specific Python versions. How can we square that with our CI?

**Comment by thomasjpfan** [comment]
We can do:

```yaml
env:
- PYTORCH_DIST="pytorch-cpu==1.3.1"
- PYTORCH_DIST="pytorch==1.4.0"

install:
...
- conda install -c pytorch ${PYTORCH_DIST}
```

**Comment by BenjaminBossan** [comment]
It seems that there are no longer dedicated `pytorch-cpu` packages. I'll just try `pytorch` instead.

**Comment by BenjaminBossan** [comment]
It seems that CI is working as expected. Therefore, I removed the draft status and updated the README.

**Pull request merged**
