### PR TITLE
Update to PyTorch 1.11.0

### PR DESCRIPTION
**Pull request by BenjaminBossan**
- Drop 1.7.1
- Update 1.10.0/1.10.1 to 1.10.2

Moreover, change all pip install instructions from `pip install` to
`python -m pip install`, which is the recommended way.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Looking at the [release notes](https://github.com/pytorch/pytorch/releases), I don't see any necessary changes on the skorch side.

We should possibly take a look at the new [TorchData](https://pytorch.org/data/beta/index.html) to see if there is anything required on the skorch side to support it or facilitate its use.

**Comment by BenjaminBossan** [comment]
Hmm, not sure why we get this error:

> ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cpu

1.11.0 for CPU seems to be listed on https://download.pytorch.org/whl/torch_stable.html :/

**Comment by thomasjpfan** [comment]
> 1.11.0 for CPU seems to be listed on https://download.pytorch.org/whl/torch_stable.html :/

Looking through the METADATA of the wheel, `1.11.0` does not support Python 3.6

**Comment by BenjaminBossan** [comment]
> Looking through the METADATA of the wheel, `1.11.0` does not support Python 3.6

Yes, that was it, thanks!

**Comment by BenjaminBossan** [comment]
@thomasjpfan Is this ready to be merged?

**Review by thomasjpfan — APPROVED** [review]
LGTM

**Pull request merged**
