### PR TITLE
Bugfix/train end cp with load init state 528

### LINKED ISSUE #528: [BUG] TrainEndCheckpoint not working with LoadInitState
I'm trying to use `TrainEndCheckpoint` with `LoadInitState` but it's not working. It doesn't even return any error as you are using `with suppress(Exception)`. The suppressed error is `*** AttributeError: 'TrainEndCheckpoint' object has no attribute 'f_history_'`, yet the file exists and `self.checkpoint.checkpoint_.f_history_==.../train_end_history.json'`.

I think the issue is that `TrainEndCheckpoint` stopped inheriting from `Checkpoint` in #463. I.e. it doesn't have a `f_history_` attribute anymore. This could be simply resolved by redirecting `self.f_history_` to `self.checkpoint_.f_history_`.

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Fixes #528 

@yanndubs Can you verify that this solves your problem?

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
I thought about such a solution but wasn't sure if `f_history_` is the only affected attribute. Instead of enumerating all, I went with the broader solution. If that can cause problems, I would, however, prefer the more specific solution.

**Comment by thomasjpfan** [comment]
I guess it is okay as long as we do not add any more parameters to `TrainEndCheckpoint`.

**Comment by BenjaminBossan** [comment]
> I guess it is okay as long as we do not add any more parameters to `TrainEndCheckpoint`.

But even that shouldn't be a problem: as long as we set the parameter as an attribute on `TrainEndCheckpoint`, `__getattr__` shouldn't be triggered.

**Comment by thomasjpfan** [comment]
Thanks for the info. (Just read up on the difference between `__getattribute__` and `__getattr__`)

**Pull request merged**
