### PR TITLE
Make cli helper work with normal sklearn estimators

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Change cli helper so that normal (i.e. non-skorch) sklearn estimators
also work. This mainly required to relax the assumption that the
estimator must have a `module` attribute.

On top, added a comment about not using positional arguments for
functions parsed by fire. The problem is that internally,
this (silently) breaks fire, so that `python foo.py --help` does not
work and instead returns the result of `python foo.py -- --help`.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
@borisdayma [CI is failing](https://github.com/skorch-dev/skorch/pull/692/checks?check_run_id=1108020723) with the following error:

```
self = <test_logging.TestWandb object at 0x7f0c324d0890>
net_cls = <class 'skorch.classifier.NeuralNetClassifier'>
classifier_module = functools.partial(<class 'skorch.toy.MLPModule'>, output_nonlin=Softmax(dim=-1), input_units=20, hidden_units=10, num_hidden=2, dropout=0.5)
data = (array([[-9.65834618e-01, -2.18907046e+00,  1.69856086e-01,
         8.13845575e-01, -3.37520909e+00, -2.14305973e+00,...0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1]))
wandb_logger_cls = <class 'skorch.callbacks.logging.WandbLogger'>
wandb_run_cls = <wandb.sdk.wandb_run.Run object at 0x7f0c32530510>
    def test_fit_with_real_experiment(
            self,
            net_cls,
            classifier_module,
            data,
            wandb_logger_cls,
            wandb_run_cls,
    ):
        net = net_cls(
            classifier_module,
            callbacks=[wandb_logger_cls(wandb_run_cls)],
            max_epochs=5,
        )
>       net.fit(*data)
skorch/tests/callbacks/test_logging.py:272: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
skorch/classifier.py:142: in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
skorch/net.py:903: in fit
    self.partial_fit(X, y, **fit_params)
skorch/net.py:862: in partial_fit
    self.fit_loop(X, y, **fit_params)
skorch/net.py:782: in fit_loop
    self.notify("on_epoch_end", **on_epoch_kwargs)
skorch/net.py:325: in notify
    getattr(cb, method_name)(self, **cb_kwargs)
skorch/callbacks/logging.py:284: in on_epoch_end
    self.wandb_run.log(logged_vals)
../../../conda/envs/skorch-env/lib/python3.7/site-packages/wandb/sdk/wandb_run.py:727: in log
    self.history._row_add(data)
../../../conda/envs/skorch-env/lib/python3.7/site-packages/wandb/sdk/wandb_history.py:34: in _row_add
    self._flush()
../../../conda/envs/skorch-env/lib/python3.7/site-packages/wandb/sdk/wandb_history.py:49: in _flush
    self._callback(row=self._data, step=self._step)
../../../conda/envs/skorch-env/lib/python3.7/site-packages/wandb/sdk/wandb_run.py:537: in _history_callback
    self._backend.interface.publish_history(row, step)
../../../conda/envs/skorch-env/lib/python3.7/site-packages/wandb/interface/interface.py:172: in publish_history
    self._publish_history(history)
../../../conda/envs/skorch-env/lib/python3.7/site-packages/wandb/interface/interface.py:162: in _publish_history
    self._publish(rec)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <wandb.interface.interface.BackendSender object at 0x7f0c324d0090>
record = history {
  item {
    key: "dur"
    value_json: "0.003249645233154297"
  }
  item {
    key: "train_loss"
    value_...  item {
    key: "_runtime"
    value_json: "3"
  }
  item {
    key: "_timestamp"
    value_json: "1599990190"
  }
}
local = None
    def _publish(self, record, local=None):
        if self._process and not self._process.is_alive():
>           raise Exception("The wandb backend process has shutdown")
E           Exception: The wandb backend process has shutdown
../../../conda/envs/skorch-env/lib/python3.7/site-packages/wandb/interface/interface.py:421: Exception
```

Locally, tests passed with `wandb==0.8.3`. CI server used `wandb==0.10.0`. Is there a possibility that this is the cause?

**Comment by borisdayma** [comment]
Yes it could be the new wandb version. Let me look into that.

In the meantime, you could set [this line](https://github.com/skorch-dev/skorch/blob/1519b557a5ec97268b8885404094a3466c735bee/skorch/tests/callbacks/test_logging.py#L217) to
`os.environ['WANDB_MODE'] = 'noop'`

**Comment by BenjaminBossan** [comment]
Thanks @borisdayma for looking into this. Do I infer correctly that setting `os.environ['WANDB_MODE'] = 'noop'` turns off wandb completely? In that case, I'd rather leave it on and pin the version to a lower one. Of course, best case scenario is to find a working fix with the current version :)

**Comment by borisdayma** [comment]
Just to let you know that we are working on a proper fix so if it is still happening you can create a separate issue and ping me (while pinning for a version that works for you).

**Comment by BenjaminBossan** [comment]
I pinned the version to <0.10.0 for now. If you have a link to an issue or PR, please post it here, then I can adjust the version as soon as the issue is fixed.

**Comment by farizrahman4u** [comment]
Fix for latest W&B here: https://github.com/skorch-dev/skorch/pull/695

**Comment by BenjaminBossan** [comment]
Since the issue was fixed, I removed the version pin for wandb.

**Review by ottonemo — APPROVED** [review]

**Review by thomasjpfan — APPROVED** [review]
LGTM

**Pull request merged**
