### PR TITLE
BUG Fixes version checks

### PR DESCRIPTION
**Pull request by thomasjpfan**
Fixes https://github.com/skorch-dev/skorch/issues/577 by using:

```py
from distutils.version import LooseVersion
```

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
I wonder, is it better than adding the pretty standard `packaging` as a dependency?

**Comment by thomasjpfan** [comment]
I am +0.5 on using the `distutils` since it is a part of python and it is fairly simple to use.

**Comment by BenjaminBossan** [comment]
According to the answers to [this question](https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python), `LooseVersion` is not compliant with the most recent PEP regarding versioning. Probably it makes no difference for us though.

I have personally no strong opinion overall. So I guess +0.5 from me as well :)

**Comment by BenjaminBossan** [comment]
@ottonemo Any opinions here? Otherwise, I think we can proceed.

**Comment by BenjaminBossan** [comment]
@thomasjpfan I think it's good to go.

**Comment by thomasjpfan** [comment]
I agree. (I normally do not merge my own PRs lol)

**Comment by BenjaminBossan** [comment]
Thx, Thomas

**Pull request merged**
