### PR TITLE
Drop official python 3.5 support

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Comes down to no longer integrating it in CI. Add Python 3.8 though.

Also: Remove a FutureWarning in LRScheduler.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
NB: Merging this PR is not urgent, since we just had the 0.9.0 release. But it should be done before the 0.10.0 release.

**Comment by thomasjpfan** [comment]
We likely want to keep python 3.5 in the CI around for bug fixes in `0.9.x` and merge right before `0.10.0` gets released.

**Comment by BenjaminBossan** [comment]
> We likely want to keep python 3.5 in the CI around for bug fixes in `0.9.x` and merge right before `0.10.0` gets released.

I wouldn't merge too late either because we want to catch bugs with Python 3.8 (or add it in a separate PR, but then CI will be very slow).

**Comment by ottonemo** [comment]
We should also think about updating the base distribution from xenial to focal (or at least bionic).
I don't think xenial as a base distribution is representative for the developer machines out there.

**Comment by BenjaminBossan** [comment]
> We should also think about updating the base distribution from xenial to focal

Good point, updated to focal.

**Comment by BenjaminBossan** [comment]
I added PyTorch 1.7.0 to travis while removing 1.3.1.

**Comment by BenjaminBossan** [comment]
@ottonemo This is pretty much obsolete after moving to github actions. Still some of the changes here should be moved to a new PR, right?

**Comment by BenjaminBossan** [comment]
Superseded by move to github actions and #733

**Pull request closed without merging**
