### PR TITLE
Add Hugging Face integration tests

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Solves #901

This PR adds a github workflow that runs integration tests with Hugging Face. These tests cover:

- using a pretrained tokenizer
- using a pretrained BERT model
- storing model artifacts on the HF model hub

The tests can be triggered manually [here](https://github.com/skorch-dev/skorch/actions) and additionally run once per week on Sundays at 9:00 AM UTC.

I'm not sure if we can really test if the workflow works before merging, any ideas?

### CODE REVIEW

**Review by thomasjpfan — COMMENTED** [review]
> I'm not sure if we can really test if the workflow works before merging, any ideas?

With a secret, I think the only way to check is to run the GitHub Action on a fork and link the results here.

**Comment by BenjaminBossan** [comment]
> With a secret, I think the only way to check is to run the GitHub Action on a fork and link the results here.

That's a good idea, I'll try it out.

**Comment by BenjaminBossan** [comment]
@thomasjpfan So I ran this on my fork of the repo and at least the manuel trigger works:

https://github.com/BenjaminBossan/inferno/actions/workflows/test-hf-integration.yml

As for the cron schedule, it didn't trigger, even though I tried different schedules. There are a few possible reasons for that:

1. GitHub is reportedly not guaranteeing that the scheduled tasks run as indicated, it's more of a perhaps thing.
2. People have reported problems based on the branch but since I merged into master, that should not be the issue.
3. It's caused by the repo being a fork.
4. I made a mistake in the workflow, even though it's pretty simple.

Anyway, I'd be willing to go ahead, worst case the cron schedule doesn't trigger, we'd still have the manual job.

Another question: Do we want to add a badge for this test to the README?

**Comment by thomasjpfan** [comment]
> Another question: Do we want to add a badge for this test to the README?

That is the simplest solution to keep track of the scheduled job.

The alternative solution is to auto-open an issue if the scheduled job fails. An example of a self contained version of this is in [pydata/xarray](https://github.com/pydata/xarray/blob/8eea8bb67bad0b5ac367c082125dd2b2519d4f52/.github/workflows/upstream-dev-ci.yaml#L132-L183).

**Comment by BenjaminBossan** [comment]
I added a badge. This is what it should look like:

https://github.com/BenjaminBossan/inferno/actions/workflows/test-hf-integration.yml/badge.svg

Other than that, I think we can also set the repo to send us notifications when an action fails, so auto-opening an issue for a feature which is not core to skorch seems to be overkill to me.

**Review by thomasjpfan — APPROVED** [review]
LGTM

**Comment by BenjaminBossan** [comment]
Just to note, the job successfully run via the scheduler: https://github.com/skorch-dev/skorch/actions/runs/3258933674. However, I couldn't figure out at what time it ran, so I'm not sure if the configured time was indeed used.

**Pull request merged**
