### PR TITLE
Support pytorch 1.5

### PR DESCRIPTION
**Pull request by BenjaminBossan**
I did not actually test this locally, will just see if CI passes. But from the changelog of PyTorch, I didn't spot anything that we would need to change on the skorch side.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Everything seems to be fine, as expected. Again, I didn't run this on GPU, so if someone could test out PyTorch 1.5 on GPU, that would be nice.

Only downside is that CI is taking really long by now. It will get worse once we add Python 3.8. I wonder how important it is for us to support Python 3.5?

**Comment by thomasjpfan** [comment]
> I wonder how important it is for us to support Python 3.5?

The ecosystem has dropped Python 3.5 by following https://numpy.org/neps/nep-0029-deprecation_policy.html

>  if someone could test out PyTorch 1.5 on GPU, that would be nice.

I'll run it.

**Comment by thomasjpfan** [comment]
Confirmed tests pass on python3.7 and python3.8 with cuda 10.2

**Comment by BenjaminBossan** [comment]
> Confirmed tests pass on python3.7 and python3.8 with cuda 10.2

Thanks a lot.

> The ecosystem has dropped Python 3.5 by following https://numpy.org/neps/nep-0029-deprecation_policy.html

I didn't know about this, thanks.

I added a future change warning to the CHANGES.md to give some adjustment time. The idea is to drop official support of Python 3.5 with the skorch 0.10.0 release. After that point, we could allow the use of f-strings and other more recent language additions.

**Pull request merged**
